//Board Description File for A2D_Relay_Board_V1.0 Board

#define A2D_RELAY_BOARD_NUM_CHANNELS	3

//LED Pin
#define A2D_RELAY_BOARD_LED_PIN					13

//Channel Pins
#define A2D_RELAY_BOARD_IO_EXP_ADDR_MIN 		0x74
#define A2D_RELAY_BOARD_IO_EXP_ADDR_MAX 		0x77
#define A2D_RELAY_BOARD_IO_EXP_ADDR_DEFAULT 	A2D_RELAY_BOARD_IO_EXP_ADDR_MIN
#define A2D_RELAY_BOARD_CH0_PIN					0
#define A2D_RELAY_BOARD_CH1_PIN					1
#define A2D_RELAY_BOARD_CH2_PIN					2
